### ISSUE TITLE
v0.6.0 release notes

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary-def#72]
https://github.com/sanctuary-js/sanctuary-def/compare/v0.5.0...v0.6.0

v0.5.0 introduced a significant regression, reported in #56. The restructuring which gave us more helpful underlining of nested types (#48) inadvertently resulted in `$.Array($.Number).test` evaluating `true` if applied to an array, *regardless of the array's values*. The solution is to use [`$.test`][1] (added in #58).

It's now much easier to see *why* a value is not a member of a particular record type (#55).

`$.create` now takes a single argument of type `{ checkTypes :: Boolean, env :: Array Type }` rather than two positional arguments (#65).

A new type constructor, [`$.Pair`][2], was introduced in #68.

[1]: https://github.com/sanctuary-js/sanctuary-def#test
[2]: https://github.com/sanctuary-js/sanctuary-def#pair

**Comment by svozza** [comment]
Fantastic. I've been looking forward to `$.Pair` dropping so I can add a `toPairs` function to sanctuary-js/sanctuary/pull/214.
